---
title: "Hearth Disease Logistic Regression"
author: "Daniel Chavarría"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's read the data

This comes from the heart disease dataset and is available at the url below, 

```{r, warning = FALSE, message = FALSE}
library(tidyverse)

raw_data <- "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data" %>% 
  read_csv(col_names = FALSE)

names(raw_data) = c(
  "age",
  "sex",# 0 = female, 1 = male
  "cp", # chest pain
  # 1 = typical angina,
  # 2 = atypical angina,
  # 3 = non-anginal pain,
  # 4 = asymptomatic
  "trestbps", # resting blood pressure (in mm Hg)
  "chol", # serum cholestoral in mg/dl
  "fbs",  # fasting blood sugar if less than 120 mg/dl, 1 = TRUE, 0 = FALSE
  "restecg", # resting electrocardiographic results
  # 1 = normal
  # 2 = having ST-T wave abnormality
  # 3 = showing probable or definite left ventricular hypertrophy
  "thalach", # maximum heart rate achieved
  "exang",   # exercise induced angina, 1 = yes, 0 = no
  "oldpeak", # ST depression induced by exercise relative to rest
  "slope", # the slope of the peak exercise ST segment
  # 1 = upsloping
  # 2 = flat
  # 3 = downsloping
  "ca", # number of major vessels (0-3) colored by fluoroscopy
  "thal", # this is short of thalium heart scan
  # 3 = normal (no cold spots)
  # 6 = fixed defect (cold spots during rest and exercise)
  # 7 = reversible defect (when cold spots only appear during exercise)
  "hd" # (the predicted attribute) - diagnosis of heart disease
  # 0 if less than or equal to 50% diameter narrowing
  # 1 if greater than 50% diameter narrowing
)
```

## Cleaning up the data

Now, we notice that some columns need to be a factor, let's get done with that

```{r, warning = FALSE}
head(raw_data)

heart_disease <- raw_data %>% 
  mutate(
    sex = case_when(sex == 1 ~ "Male",
                    sex == 0 ~ "Female"),
    sex = as_factor(sex),
    cp = as_factor(cp),
    fbs = as_factor(fbs),
    restecg = as_factor(restecg),
    exang = as_factor(exang), 
    slope = as_factor(slope),
    ca = as.integer(ca) %>% as_factor(),
    thal = as.integer(thal) %>% as_factor(),
    hd = case_when(hd == 0 ~ "Healthy",
                   hd >= 1 ~ "Unhealthy") %>% as_factor()
    
         )

head(heart_disease)
```

Now, every variable is way clearer and we can start doing some processing.
